name: Manual Android Debug Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Debug APK
        # We use the 'development' profile from your eas.json
        run: npx eas-cli build --platform android --profile development --local
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Upload Debug APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: authenticator-debug-apk
          # This looks for any .apk file generated in the android build folder
          path: "**/*.apk"
          retention-days: 1
